version: 2
jobs:
  build:
    branches:
      only:
        - develop
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn -version
      - run: mvn clean package integration-test

      #commands:
          #  configure-gpg:
          #    steps:
          #      - run:
          #          name: Configure GPG private key for signing project artifacts in OSS Sonatype
        #          command: |
        #            echo $SECRING_GPG_ASC_BASE64 | base64 --decode | gpg --batch --no-tty --import --yes
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
